20210822 howto (#63)
* quick fix for debug build

Fix for compilation warning:
error: comparison of array 'args' equal to a null pointer is always
false

* Update to HOWTO

Updating HOWTO for make commands to use for areg-sdk compilation with
different settings/configurations